repos:
- repo: https://github.com/hootsuite/pre-commit-php.git
  rev: 1.1.0
  hooks:
  - id: php-cs
    files: \.(php)$
    args: [--standard=moodle -p]
  - id: php-cbf
    files: \.(php)$
    args: [--standard=moodle -p]